import { useState } from "react";
import type { CompatibleModel, Grade, HardwareProfile } from "../types";
import { GRADE_STATUS } from "../lib/compatibility";
import { exportCsv, exportJson } from "../lib/export";

interface Props {
  hardware: HardwareProfile;
  allModels: CompatibleModel[];
  calibrationFactor?: number;
}

const GRADE_ORDER: Grade[] = ["S", "A", "B", "C", "D", "F"];

const TIER_COLORS: Record<Grade, { bg: string; text: string; border: string }> =
  {
    S: {
      bg: "bg-emerald-500",
      text: "text-white",
      border: "border-emerald-200 dark:border-emerald-800",
    },
    A: {
      bg: "bg-blue-500",
      text: "text-white",
      border: "border-blue-200 dark:border-blue-800",
    },
    B: {
      bg: "bg-brand-500",
      text: "text-white",
      border: "border-brand-200 dark:border-brand-500",
    },
    C: {
      bg: "bg-amber-500",
      text: "text-white",
      border: "border-amber-200 dark:border-amber-800",
    },
    D: {
      bg: "bg-red-500",
      text: "text-white",
      border: "border-red-200 dark:border-red-800",
    },
    F: {
      bg: "bg-zinc-400 dark:bg-zinc-600",
      text: "text-white",
      border: "border-zinc-200 dark:border-zinc-700",
    },
  };

function formatToks(toks: number): string {
  if (toks >= 100) return ">100 tok/s";
  if (toks >= 1) return `~${Math.round(toks)} tok/s`;
  return "<1 tok/s";
}

function formatContext(tokens: number): string {
  if (tokens >= 131072) return "128K";
  if (tokens >= 65536) return "64K";
  if (tokens >= 32768) return "32K";
  if (tokens >= 16384) return "16K";
  if (tokens >= 8192) return "8K";
  return "2K";
}

export function TierList({
  hardware,
  allModels,
  calibrationFactor = 1,
}: Props) {
  const [copied, setCopied] = useState(false);

  const tag = hardware.hasGpu
    ? `gpu-${hardware.vram}gb-ram-${hardware.ram}gb`
    : `cpu-ram-${hardware.ram}gb`;

  const byGrade = GRADE_ORDER.reduce(
    (acc, g) => ({ ...acc, [g]: allModels.filter((m) => m.grade === g) }),
    {} as Record<Grade, CompatibleModel[]>,
  );

  const hwLabel = hardware.hasGpu
    ? `${hardware.vram} GB VRAM · ${hardware.ram} GB RAM`
    : `${hardware.ram} GB RAM (CPU only)`;

  function handleCopy() {
    const lines: string[] = [`Hardware: ${hwLabel}`, ""];
    for (const grade of GRADE_ORDER) {
      const items = byGrade[grade];
      if (!items.length) continue;
      lines.push(`=== ${grade} — ${GRADE_STATUS[grade]} ===`);
      for (const item of items) {
        const mem = item.runOnGpu
          ? `${item.bestVariant.vramRequired} GB VRAM`
          : `${item.bestVariant.ramRequired} GB RAM`;
        const speed = item.fits
          ? formatToks(item.tokensPerSec * calibrationFactor)
          : "Too heavy";
        const ctx = formatContext(item.model.contextLength) + " ctx";
        const name = `${item.model.name} (${item.bestVariant.quantization})`;
        lines.push(
          `  ${name.padEnd(38)} ${speed.padEnd(14)} ${mem.padEnd(12)} ${ctx}`,
        );
      }
      lines.push("");
    }
    lines.push("Generated by LLM Evaluator");
    navigator.clipboard.writeText(lines.join("\n")).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  return (
    <div>
      <div className="flex items-center justify-between mb-4">
        <div>
          <h2 className="text-lg font-bold text-zinc-900 dark:text-zinc-100">
            Tier List
          </h2>
          <p className="text-xs text-zinc-500 dark:text-zinc-400 mt-0.5">
            {hwLabel} · {allModels.filter((m) => m.fits).length}/
            {allModels.length} models fit
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() =>
              exportCsv(
                allModels.filter((m) => m.fits),
                tag,
              )
            }
            className="text-xs px-3 py-1.5 rounded-lg bg-zinc-100 dark:bg-zinc-800 text-zinc-600 dark:text-zinc-400 hover:bg-zinc-200 dark:hover:bg-zinc-700 transition-colors cursor-pointer font-medium"
          >
            CSV
          </button>
          <button
            onClick={() =>
              exportJson(
                allModels.filter((m) => m.fits),
                tag,
              )
            }
            className="text-xs px-3 py-1.5 rounded-lg bg-zinc-100 dark:bg-zinc-800 text-zinc-600 dark:text-zinc-400 hover:bg-zinc-200 dark:hover:bg-zinc-700 transition-colors cursor-pointer font-medium"
          >
            JSON
          </button>
          <button
            onClick={handleCopy}
            className="text-xs px-3 py-1.5 rounded-lg bg-zinc-100 dark:bg-zinc-800 text-zinc-600 dark:text-zinc-400 hover:bg-zinc-200 dark:hover:bg-zinc-700 transition-colors cursor-pointer font-medium"
          >
            {copied ? "Copied!" : "Copy as text"}
          </button>
        </div>
      </div>

      <div className="space-y-3">
        {GRADE_ORDER.map((grade) => {
          const items = byGrade[grade];
          if (!items.length) return null;
          const colors = TIER_COLORS[grade];
          return (
            <div
              key={grade}
              className={`rounded-2xl border ${colors.border} overflow-hidden`}
            >
              {/* Tier header */}
              <div
                className={`${colors.bg} ${colors.text} px-4 py-2 flex items-center gap-3`}
              >
                <span className="text-xl font-black w-7 text-center">
                  {grade}
                </span>
                <span className="font-semibold text-sm">
                  {GRADE_STATUS[grade]}
                </span>
                <span className="ml-auto text-xs opacity-80 font-medium">
                  {items.length} model{items.length !== 1 ? "s" : ""}
                </span>
              </div>

              {/* Models */}
              <div className="divide-y divide-zinc-100 dark:divide-zinc-800">
                {items.map((item) => (
                  <div
                    key={item.model.id}
                    className="flex items-center gap-3 px-4 py-2.5 bg-white dark:bg-zinc-900 hover:bg-zinc-50 dark:hover:bg-zinc-800/50 transition-colors"
                  >
                    {/* Score */}
                    {item.fits ? (
                      <span className="text-xs font-bold text-zinc-500 dark:text-zinc-400 w-8 text-right shrink-0">
                        {item.score}
                      </span>
                    ) : (
                      <span className="text-xs text-zinc-300 dark:text-zinc-600 w-8 text-right shrink-0">
                        —
                      </span>
                    )}

                    {/* Name + params */}
                    <div className="min-w-0 flex-1">
                      <span className="text-sm font-medium text-zinc-900 dark:text-zinc-100">
                        {item.model.name}
                      </span>
                      <span className="text-xs text-zinc-400 ml-1.5">
                        {item.model.parameters}B
                      </span>
                    </div>

                    {/* Quant */}
                    <span className="text-xs text-zinc-400 font-mono shrink-0 hidden sm:block">
                      {item.bestVariant.quantization}
                    </span>

                    {/* Speed or "Too heavy" */}
                    {item.fits ? (
                      <span className="text-xs font-medium text-zinc-600 dark:text-zinc-300 shrink-0 w-20 text-right">
                        {formatToks(item.tokensPerSec * calibrationFactor)}
                      </span>
                    ) : (
                      <span className="text-xs text-zinc-400 shrink-0 w-20 text-right">
                        Too heavy
                      </span>
                    )}

                    {/* Memory */}
                    <span className="text-xs text-zinc-400 shrink-0 w-16 text-right hidden md:block">
                      {item.fits
                        ? `${item.runOnGpu ? item.bestVariant.vramRequired : item.bestVariant.ramRequired} GB`
                        : `${item.bestVariant.vramRequired} GB min`}
                    </span>

                    {/* Context */}
                    <span className="text-xs text-zinc-400 shrink-0 hidden lg:block">
                      {formatContext(item.model.contextLength)} ctx
                    </span>
                  </div>
                ))}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
